import { Dimensions, Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 32,
    height: Dimensions.get("window").height,
  },
  headerContainer: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    width: Dimensions.get("window").width,
    paddingVertical: 11,
    backgroundColor: "#ffffff",
    marginTop: Platform.OS === "ios" ? 10 : 0,
    marginBottom: 32,
    borderBottomColor: "rgba(0, 0, 0, 0.3)",
    borderBottomWidth: 0.5,
  },
  headerTitle: {
    fontFamily: "Roboto-Medium",
    fontSize: 17,
    lineHeight: 22,
    color: "#212121",
    letterSpacing: -0.408,
  },
  goBackButton: {
    position: "absolute",
    bottom: 11,
    left: 16,
  },
  wrapMain: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  wrapForm: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
  },
  containerImage: {},
  wrapImage: {
    position: "relative",
    height: 240,
    width: Dimensions.get("window").width - 32,
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    marginBottom: 8,
    overflow: "hidden",
  },
  camera: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  addImage: {
    width: 60,
    height: 60,
    backgroundColor: "#fff",
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  wrapPhoto: {
    width: "100%",
    height: "100%",
  },
  photo: {
    width: "100%",
    height: 240,
    resizeMode: "cover",
  },
  cameraIcon: {},
  textImage: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#BDBDBD",
  },
  form: {
    width: "100%",
    marginTop: 32,
    backgroundColor: "#fff",
  },
  input: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    height: 50,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
    color: "#212121",
  },
  button: {
    marginTop: 16,
    height: 51,
    backgroundColor: "#F6F6F6",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonTitle: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#BDBDBD",
  },
  trashButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 70,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F6F6F6",
    marginTop: Platform.OS === "ios" ? 145 : 85,
  },
});
